"""
Mapping between common organ names (from LLM/STT) and TotalSegmentator class names & Label IDs.
Reference: https://github.com/wasserth/TotalSegmentator#class-details
"""

# Label IDs for TotalSegmentator v1/v2 (standard 'total' task)
# Format: "class_name": label_id
TOTAL_SEGMENTATOR_LABELS = {
    "spleen": 1,
    "kidney_right": 2,
    "kidney_left": 3,
    "gallbladder": 4,
    "liver": 5,
    "stomach": 6,
    "aorta": 7,
    "inferior_vena_cava": 8,
    "portal_vein_and_splenic_vein": 9,
    "pancreas": 10,
    "adrenal_gland_right": 11,
    "adrenal_gland_left": 12,
    "lung_upper_lobe_left": 13,
    "lung_lower_lobe_left": 14,
    "lung_upper_lobe_right": 15,
    "lung_middle_lobe_right": 16,
    "lung_lower_lobe_right": 17,
    "vertebrae_L5": 18,
    "vertebrae_L4": 19,
    "vertebrae_L3": 20,
    "vertebrae_L2": 21,
    "vertebrae_L1": 22,
    "vertebrae_T12": 23,
    "vertebrae_T11": 24,
    "vertebrae_T10": 25,
    "vertebrae_T9": 26,
    "vertebrae_T8": 27,
    "vertebrae_T7": 28,
    "vertebrae_T6": 29,
    "vertebrae_T5": 30,
    "vertebrae_T4": 31,
    "vertebrae_T3": 32,
    "vertebrae_T2": 33,
    "vertebrae_T1": 34,
    "vertebrae_C7": 35,
    "vertebrae_C6": 36,
    "vertebrae_C5": 37,
    "vertebrae_C4": 38,
    "vertebrae_C3": 39,
    "vertebrae_C2": 40,
    "vertebrae_C1": 41,
    "esophagus": 42,
    "trachea": 43,
    "heart_myocardium": 44,
    "heart_atrium_left": 45,
    "heart_ventricle_left": 46,
    "heart_atrium_right": 47,
    "heart_ventricle_right": 48,
    "pulmonary_artery": 49,
    "brain": 50,
    "iliac_artery_left": 51,
    "iliac_artery_right": 52,
    "iliac_vein_left": 53,
    "iliac_vein_right": 54,
    "small_bowel": 55,
    "duodenum": 56,
    "colon": 57,
    "rib_left_1": 58,
    "rib_left_2": 59,
    "rib_left_3": 60,
    "rib_left_4": 61,
    "rib_left_5": 62,
    "rib_left_6": 63,
    "rib_left_7": 64,
    "rib_left_8": 65,
    "rib_left_9": 66,
    "rib_left_10": 67,
    "rib_left_11": 68,
    "rib_left_12": 69,
    "rib_right_1": 70,
    "rib_right_2": 71,
    "rib_right_3": 72,
    "rib_right_4": 73,
    "rib_right_5": 74,
    "rib_right_6": 75,
    "rib_right_7": 76,
    "rib_right_8": 77,
    "rib_right_9": 78,
    "rib_right_10": 79,
    "rib_right_11": 80,
    "rib_right_12": 81,
    "humerus_left": 82,
    "humerus_right": 83,
    "scapula_left": 84,
    "scapula_right": 85,
    "clavicula_left": 86,
    "clavicula_right": 87,
    "femur_left": 88,
    "femur_right": 89,
    "hip_left": 90,
    "hip_right": 91,
    "sacrum": 92,
    "face": 93,
    "gluteus_maximus_left": 94,
    "gluteus_maximus_right": 95,
    "gluteus_medius_left": 96,
    "gluteus_medius_right": 97,
    "gluteus_minimus_left": 98,
    "gluteus_minimus_right": 99,
    "autochthon_left": 100,
    "autochthon_right": 101,
    "iliopsoas_left": 102,
    "iliopsoas_right": 103,
    "urinary_bladder": 104
}

ORGAN_MAPPING = {
    # Standard TotalSegmentator classes (lowercase)
    "spleen": "spleen",
    "kidney_right": "kidney_right",
    "kidney_left": "kidney_left",
    "gallbladder": "gallbladder",
    "liver": "liver",
    "stomach": "stomach",
    "pancreas": "pancreas",
    "adrenal_gland_right": "adrenal_gland_right",
    "adrenal_gland_left": "adrenal_gland_left",
    "lung_upper_lobe_left": "lung_upper_lobe_left",
    "lung_lower_lobe_left": "lung_lower_lobe_left",
    "lung_upper_lobe_right": "lung_upper_lobe_right",
    "lung_middle_lobe_right": "lung_middle_lobe_right",
    "lung_lower_lobe_right": "lung_lower_lobe_right",
    "esophagus": "esophagus",
    "trachea": "trachea",
    "thyroid_gland": "thyroid_gland",
    "small_bowel": "small_bowel",
    "duodenum": "duodenum",
    "colon": "colon",
    "urinary_bladder": "urinary_bladder",
    "prostate": "prostate",
    "kidney_cyst_left": "kidney_cyst_left",
    "kidney_cyst_right": "kidney_cyst_right",
    "sacrum": "sacrum",
    "vertebrae": "vertebrae_L1", # Generic mapping to one vertebra for now
    "heart": "heart_myocardium", # Map generic heart to myocardium
    "aorta": "aorta",
    "pulmonary_vein": "pulmonary_vein",
    "brachiocephalic_trunk": "brachiocephalic_trunk",
    "subclavian_artery_right": "subclavian_artery_right",
    "subclavian_artery_left": "subclavian_artery_left",
    "common_carotid_artery_right": "common_carotid_artery_right",
    "common_carotid_artery_left": "common_carotid_artery_left",
    "brachiocephalic_vein_left": "brachiocephalic_vein_left",
    "brachiocephalic_vein_right": "brachiocephalic_vein_right",
    "atrial_appendage_left": "atrial_appendage_left",
    "superior_vena_cava": "superior_vena_cava",
    "inferior_vena_cava": "inferior_vena_cava",
    "portal_vein_and_splenic_vein": "portal_vein_and_splenic_vein",
    "iliac_artery_left": "iliac_artery_left",
    "iliac_artery_right": "iliac_artery_right",
    "iliac_vein_left": "iliac_vein_left",
    "iliac_vein_right": "iliac_vein_right",
    "humerus_left": "humerus_left",
    "humerus_right": "humerus_right",
    "scapula_left": "scapula_left",
    "scapula_right": "scapula_right",
    "clavicula_left": "clavicula_left",
    "clavicula_right": "clavicula_right",
    "femur_left": "femur_left",
    "femur_right": "femur_right",
    "hip_left": "hip_left",
    "hip_right": "hip_right",
    "spinal_cord": "spinal_cord",
    "gluteus_maximus_left": "gluteus_maximus_left",
    "gluteus_maximus_right": "gluteus_maximus_right",
    "gluteus_medius_left": "gluteus_medius_left",
    "gluteus_medius_right": "gluteus_medius_right",
    "gluteus_minimus_left": "gluteus_minimus_left",
    "gluteus_minimus_right": "gluteus_minimus_right",
    "autochthon_left": "autochthon_left",
    "autochthon_right": "autochthon_right",
    "iliopsoas_left": "iliopsoas_left",
    "iliopsoas_right": "iliopsoas_right",
    "brain": "brain",
    "skull": "skull",
    "sternum": "sternum",
    "costal_cartilages": "costal_cartilages",
    
    # English Variations / Synonyms
    "right kidney": "kidney_right",
    "left kidney": "kidney_left",
    "kidney": "kidney_right", # Default
    "right adrenal gland": "adrenal_gland_right",
    "left adrenal gland": "adrenal_gland_left",
    "gall bladder": "gallbladder",
    "small intestine": "small_bowel",
    "bowel": "small_bowel",
    "bowel loops": "small_bowel",
    "bladder": "urinary_bladder",
    "right lung": "lung_upper_lobe_right", 
    "left lung": "lung_upper_lobe_left", 
    "lungs": "lung_upper_lobe_right",
    "right lung base": "lung_lower_lobe_right",
    "lung base": "lung_lower_lobe_right",
    "right base": "lung_lower_lobe_right",
    "heart": "heart_myocardium",
    "stomach": "stomach",
    "pancreas": "pancreas",
    "spleen": "spleen",
    "spine": "vertebrae_L1",
    "lumbar spine": "vertebrae_L1",
    "abdominal aorta": "aorta",
    "blood vessels": "aorta", # Generic mapping
    "appendix": "colon", # Appendix is part of colon usually, TS might not have specific class
    "renal artery": "aorta", # Not specifically segmented in basic task
    
    # Vietnamese Variations
    "gan": "liver",
    "thận phải": "kidney_right",
    "thận trái": "kidney_left",
    "thận": "kidney_right", 
    "lá lách": "spleen",
    "lách": "spleen",
    "túi mật": "gallbladder",
    "mật": "gallbladder",
    "tụy": "pancreas",
    "tuyến tụy": "pancreas",
    "dạ dày": "stomach",
    "bao tử": "stomach",
    "phổi phải": "lung_upper_lobe_right", 
    "phổi trái": "lung_upper_lobe_left", 
    "phổi": "lung_upper_lobe_right", 
    "đáy phổi": "lung_lower_lobe_right",
    "tim": "heart_myocardium",
    "bàng quang": "urinary_bladder",
    "tuyến tiền liệt": "prostate",
    "đại tràng": "colon",
    "ruột già": "colon",
    "ruột non": "small_bowel",
    "ruột": "small_bowel",
    "thực quản": "esophagus",
    "khí quản": "trachea",
    "động mạch chủ": "aorta",
    "động mạch chủ bụng": "aorta",
    "xương sống": "vertebrae_L1",
    "cột sống": "vertebrae_L1",
}

def get_totalsegmentator_class(organ_name: str) -> tuple:
    """
    Map an organ name (English or Vietnamese) to a TotalSegmentator class name and Label ID.
    Returns (class_name, label_id) or (None, None) if no match found.
    """
    if not organ_name:
        return None, None
        
    normalized_name = organ_name.lower().strip()
    
    ts_class = None
    
    # Direct check
    if normalized_name in ORGAN_MAPPING:
        ts_class = ORGAN_MAPPING[normalized_name]
    
    if ts_class and ts_class in TOTAL_SEGMENTATOR_LABELS:
        return ts_class, TOTAL_SEGMENTATOR_LABELS[ts_class]
    
    # Fallback: check if normalized name is itself a valid class
    if normalized_name in TOTAL_SEGMENTATOR_LABELS:
        return normalized_name, TOTAL_SEGMENTATOR_LABELS[normalized_name]
        
    return None, None
